# .readthedocs.yml

version: 2

build:
  image: latest

sphinx:
  configuration: conf.py

search:
   ignore:
     - .github/
     - README.md

formats: all

python:
  version: "3.7"

  system_packages: true

  install:
    - requirements: requirements.txt

