name: release

on:
  create:
    tags:
      - v*

jobs:
  tagged-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release for new Tag
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Plex Meta Manager Wiki ${{ github.event.ref }}
          repo_token: ${{ secrets.PAT }}
          prerelease: false